### PR TITLE
Feature/dx 955 add ci entrypoint

### PR DESCRIPTION
**Pull request by NullableInt**
Does the git branch things, also calls the original entrypoin with "jekyll build" because I found it neat, hope it works

### CODE REVIEW

**Comment by NullableInt** [comment]
Speed demon

**Comment by NullableInt** [comment]
I merged it, but it was registered as a close here?

**Comment by asbjornu** [comment]
Did you merge it on GitHub? If you merge locally, it sometimes doesn't get registered as merged on GitHub.

**Comment by NullableInt** [comment]
I did it locally 😢

**Pull request closed without merging**
